[package]
name = "td-free-rs"
version = "0.1.0"
authors = ["Mawoka <git@mawoka.eu>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "td-free-rs"
harness = false     # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"
codegen-units = 1
panic = "abort"
lto = true
strip = true

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
# ota = ["dep:esp-ota"]
default = ["std", "esp-idf-svc/native"]
#critical-section-impl = ["critical-section/restore-state-none"]

pio = ["esp-idf-svc/pio"]
std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]

[dependencies]
log = { version = "0.4", default-features = false }
esp-idf-svc = { version = "0.51", default-features = false, features= ["experimental", "embassy-time-driver"] }
embedded-hal = "1"
heapless = "0.8"
edge-http = {version = "0.5", features = ["embedded-svc"]}
embedded-io-async = { version = "0.6", default-features = false }
edge-nal-std = {version = "0.5"}
edge-nal = "0.5"
edge-ws = "0.4"
futures-lite = "2.6"


anyhow = "1"
url = "2.5"


veml7700 = "0.2.0"
embassy-time = { version = "0.4.0", features = ["log", "std", "generic-queue-8"] }

[build-dependencies]
embuild = {version = "0.33.0", features = ["espidf"]}
vergen-gix = { version = "1", features = ["build", "rustc"] }
anyhow = "1"
cc = "=1.1.20"

# [package.metadata.espflash]
# partition_table = "partitions.csv"
