name: PlatformIO CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Install ESPtool
        run: pip install esptool
      - name: Build PlatformIO Project
        run: pio run
      - name: Combine into single file
        run: esptool.py --chip esp32c3 merge_bin -o td-free.bin --flash_size 4MB 0x1000 .pio/build/mini_c3/bootloader.bin 0x8000 .pio/build/mini_c3/partitions.bin 0x10000 .pio/build/mini_c3/firmware.bin
      - name: Upload esp32c3
        uses: actions/upload-artifact@v4
        with:
          path: ./td-free.bin
          name: esp32c3-4mb
