name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run
      - name: Upload normal esp32
        uses: actions/upload-artifact@v4
        with:
          path: .pio/build/d1_mini/firmware.bin
          name: firmware-esp32.bin
      - name: Upload esp32c3
        uses: actions/upload-artifact@v4
        with:
          path: .pio/build/mini_c3/firmware.bin
          name: firmware-esp32c3.bin
